spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/webstoredb
    username: webstoreuser
    password: testing
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration